name: Test (PyPI)

on:
  schedule:
    - cron: "0 18 * * 5"

jobs:
  test:
    name: Test PyPI (${{ matrix.os }}, py${{ matrix.python-version }}, tf${{ matrix.tensorflow }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        tensorflow: [1, 2]
        exclude:
          - python-version: '3.10'
            tensorflow: 1
          - python-version: '3.9'
            tensorflow: 1
          - python-version: '3.8'
            tensorflow: 1

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pip install "tensorflow==${{ matrix.tensorflow }}.*"
      - uses: actions/checkout@v2
      - if: matrix.tensorflow == 1
        run: pip install "csbdeep[test,tf1]"
      - if: matrix.tensorflow == 2
        run: pip install "csbdeep[test]"
      - run: pytest -v --durations=50