name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        tensorflow: ["tensorflow", "'tensorflow<2' 'keras<2.4'"]
        exclude:
          - python-version: 3.9
            tensorflow: "'tensorflow<2' 'keras<2.4'"
          - python-version: 3.8
            tensorflow: "'tensorflow<2' 'keras<2.4'"
          - python-version: 2.7
            tensorflow: "tensorflow"
          - python-version: 2.7
            tensorflow: "'tensorflow<2' 'keras<2.4'"
            os: windows-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip wheel setuptools

      - if: ${{ matrix.python-version == 2.7 }}
        run: pip install --prefer-binary ${{ matrix.tensorflow }}
      - if: ${{ matrix.python-version != 2.7 }}
        run: pip install ${{ matrix.tensorflow }}

      - uses: actions/checkout@v2

      - if: ${{ matrix.python-version == 2.7 }}
        run: pip install --prefer-binary ".[test]"
      - if: ${{ matrix.python-version != 2.7 }}
        run: pip install ".[test]"

      - run: pytest -v --durations=50