name: Test (Legacy)

on:
  schedule:
    - cron: "0 18 * * 5"

jobs:
  test-legacy:
    runs-on: ubuntu-20.04
    name: Legacy (${{ matrix.tensorflow }}, ${{ matrix.keras }})
    strategy:
      fail-fast: false
      matrix:
        # As a general rule, the latest release of Keras is compatible with the latest
        # release of TensorFlow as well as the previous release of TensorFlow (in most
        # cases, it is actually compatible with several prior TF releases, but that is
        # not guaranteed).
        #
        # -- https://github.com/keras-team/keras/issues/10440#issuecomment-397428200
        include:
          - python-version: 3.6
            tensorflow: "tensorflow<1.15"
            keras: "keras==2.3.0"
          - python-version: 3.6
            tensorflow: "tensorflow<1.14"
            keras: "keras==2.2.5"
          - python-version: 3.6
            tensorflow: "tensorflow<1.13"
            keras: "keras==2.2.5"
          - python-version: 3.6
            tensorflow: "tensorflow<1.12"
            keras: "keras==2.2.5"
          - python-version: 3.6
            # true at some point in the past: tensorflow 1.10 requires numpy <= 1.14.5, which causes problems -> not supported
            # https://github.com/tensorflow/tensorflow/blob/v1.10.1/tensorflow/tools/pip_package/setup.py#L54
            tensorflow: "tensorflow<1.11"
            keras: "keras==2.2.4"
          - python-version: 3.6
            tensorflow: "tensorflow<1.10"
            keras: "keras==2.2.2"
          # - python-version: 3.6
          #   # causes segmentation fault...
          #   tensorflow: "tensorflow<1.9"
          #   keras: "keras==2.2.0"
          - python-version: 3.6
            tensorflow: "tensorflow<1.8"
            keras: "keras==2.2.0"
          - python-version: 3.6
            tensorflow: "tensorflow<1.8"
            keras: "keras==2.1.6"
          - python-version: 3.6
            # lowest supported keras version, last tensorflow release that supports CUDA 8
            tensorflow: "tensorflow==1.4.1"
            keras: "keras==2.1.2"

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pip install "${{ matrix.tensorflow }}" "${{ matrix.keras }}"
      - uses: actions/checkout@v3
      - run: pip install "csbdeep[tf1,test]"
      - run: pytest -v --durations=50